title: Studying Inexorably
author: Manda-Jayne Davies
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Tracking the progress of one person's learning.

# social links
twitter_username: your-twitter-handle
github_username:  mandajaynedavies

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
